# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sd < Formula
  desc "Generate split-horizon DNS (Pi-hole/dnsmasq) and Caddy site blocks from a declarative services.yaml"
  homepage "https://github.com/Miista/homebrew-sd"
  version "0.9.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Miista/homebrew-sd/releases/download/v0.9.2/sd_0.9.2_darwin_amd64.tar.gz"
      sha256 "0e735fc40bfd1d88a121a72ca966e37448163b8dbd504bc846fb2f34e8ffaaea"

      define_method(:install) do
        bin.install "sd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Miista/homebrew-sd/releases/download/v0.9.2/sd_0.9.2_darwin_arm64.tar.gz"
      sha256 "e8b394899e41c75fd2906806325e2359c3b322f2e2fcc6d8c06a6aa7daa904dc"

      define_method(:install) do
        bin.install "sd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Miista/homebrew-sd/releases/download/v0.9.2/sd_0.9.2_linux_amd64.tar.gz"
      sha256 "29da24b63ffb44aa9e521831a0d95bc028cfb1f4d6f14bda1d0bfe5342e8a2e0"
      define_method(:install) do
        bin.install "sd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Miista/homebrew-sd/releases/download/v0.9.2/sd_0.9.2_linux_arm64.tar.gz"
      sha256 "b333021920af5f116d02a9ab6c3806378bd48161f00dddf112fa663a99f5b6f0"
      define_method(:install) do
        bin.install "sd"
      end
    end
  end

  test do
    assert_match "sd", shell_output("#{bin}/sd version")
  end
end
