# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sd < Formula
  desc "Generate split-horizon DNS (Pi-hole/dnsmasq) and Caddy site blocks from a declarative services.yaml"
  homepage "https://github.com/Miista/homebrew-sd"
  version "0.9.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Miista/homebrew-sd/releases/download/v0.9.3/sd_0.9.3_darwin_amd64.tar.gz"
      sha256 "bac9452d9922a1ddc981c0dc90a012c693beb278919c04664e9fb6ebebd80743"

      define_method(:install) do
        bin.install "sd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Miista/homebrew-sd/releases/download/v0.9.3/sd_0.9.3_darwin_arm64.tar.gz"
      sha256 "182f436726d30a4b80d315cba69cd80e59dc108757c934a2ebe2393fea326aad"

      define_method(:install) do
        bin.install "sd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Miista/homebrew-sd/releases/download/v0.9.3/sd_0.9.3_linux_amd64.tar.gz"
      sha256 "de0f724eb473f753aa8b92e60e007cb35e36a84da3d0f3d7390317e7e6c7f254"
      define_method(:install) do
        bin.install "sd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Miista/homebrew-sd/releases/download/v0.9.3/sd_0.9.3_linux_arm64.tar.gz"
      sha256 "c29aaa56ccb5909135f0da600a80bb8c0fb862838ab16d12db97f85915f29811"
      define_method(:install) do
        bin.install "sd"
      end
    end
  end

  test do
    assert_match "sd", shell_output("#{bin}/sd version")
  end
end
