# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shd < Formula
  desc "Generate split-horizon DNS (Pi-hole/dnsmasq) and Caddy site blocks from a declarative services.yaml"
  homepage "https://github.com/Miista/homebrew-shd"
  version "0.6.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Miista/homebrew-shd/releases/download/v0.6.1/shd_0.6.1_darwin_amd64.tar.gz"
      sha256 "213f4f242807606474cc67afdb782ab199ee10e28d57149ef945dc49b8af1d63"

      define_method(:install) do
        bin.install "shd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Miista/homebrew-shd/releases/download/v0.6.1/shd_0.6.1_darwin_arm64.tar.gz"
      sha256 "8e6528d7276a1e7ddaf8d2bd02f1fc369ae24f2acb9fb431dc53633f9aa6f10a"

      define_method(:install) do
        bin.install "shd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Miista/homebrew-shd/releases/download/v0.6.1/shd_0.6.1_linux_amd64.tar.gz"
      sha256 "b18afed4014917ff965ee74d1a3042d9559d3adb04fd55ca8528c0b86df43500"
      define_method(:install) do
        bin.install "shd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Miista/homebrew-shd/releases/download/v0.6.1/shd_0.6.1_linux_arm64.tar.gz"
      sha256 "3a0ccc4cc16407848af42e7d4342497d316af56eb753a069fc933a4570d0c33f"
      define_method(:install) do
        bin.install "shd"
      end
    end
  end

  test do
    assert_match "shd", shell_output("#{bin}/shd version")
  end
end
