# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shd < Formula
  desc "Generate split-horizon DNS (Pi-hole/dnsmasq) and Caddy site blocks from a declarative services.yaml"
  homepage "https://github.com/Miista/homebrew-shd"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Miista/homebrew-shd/releases/download/v0.3.0/shd_0.3.0_darwin_amd64.tar.gz"
      sha256 "0f92c971550261658743db50f2d8ac4e9bbfa7b42d9ccfd5297b45709151e5d7"

      define_method(:install) do
        bin.install "shd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Miista/homebrew-shd/releases/download/v0.3.0/shd_0.3.0_darwin_arm64.tar.gz"
      sha256 "76466af05f757cd5aa4831866bc1b4d18e4aca10df8336e2d62c58947eab2e70"

      define_method(:install) do
        bin.install "shd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Miista/homebrew-shd/releases/download/v0.3.0/shd_0.3.0_linux_amd64.tar.gz"
      sha256 "8d468d75712b138f7f2c0a3a659df9919fd13857520374b7bf84bd1cb6d69793"
      define_method(:install) do
        bin.install "shd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Miista/homebrew-shd/releases/download/v0.3.0/shd_0.3.0_linux_arm64.tar.gz"
      sha256 "6475e9c358581bbb783453cbda5bd210e8bccbcb6eb09795b5483eabc84deba5"
      define_method(:install) do
        bin.install "shd"
      end
    end
  end

  test do
    assert_match "shd", shell_output("#{bin}/shd version")
  end
end
